server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://129.211.6.38:3306/product?useSSL=false&serverTimezone=UTC
    username: root
    password: Lg5181349!!
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      test-on-borrow: true
      validation-query: SELECT 1

mybatis:
  type-aliases-package: com.dingtalk.model
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true



logging:
  level:
    root: INFO
pagehelper:
  helper-dialect: mysql


dingtalk:
  app_key: dingq87y6ea5ydh9lepl
  app_secret: H4oJrL21_rd-UkfXONTh1CcFUm0qxLPs91QYJyKyDBJm6sRzPLOb0QvGaHU7dOHR
  corp_id: dingeca80627ed9718e0bc961a6cb783455b
  agent_id: 2995946851
